config/routes.rb
Rails.application.routes.draw do
  resources :valor_usts

  authenticate :user do

    resources :os_tipos, only: [:new, :create, :edit, :update, :destroy]

    resources :os_tarefas do
      collection do
      get 'mostra_nao_pagas'
      get 'mostra_nao_pagas_aprovadas_os'
    end
end

    get '/set_situacao_tarefa' => 'os_tarefas#set_situacao', as: 'set_situacao_tarefa'
    resources :tarefa_deb_tecnicos

    resources :projetos

    resources :produtos

    resources :pessoas

    resources :os_nivel_servicos

    resources :os_entregavels

    resources :os_deb_tecnicos

    resources :ordem_servicos

    resources :entregavels

    resources :debito_tecnicos

    resources :catalogos

  end

  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :models


  root to: 'visitors#index'

  match 'imprimir', controller: 'ordem_servicos', action: 'imprimir', via: 'get'
  match 'clonar', controller: 'ordem_servicos', action: 'clone', via: 'get'
  match 'laudo', controller: 'laudos', action: 'laudo', via: 'get'

end

app/models/os_deb_tecnico.rb
class OsDebTecnico < ActiveRecord::Base
  audited
  belongs_to :debito_tecnico, class_name: "DebitoTecnico", foreign_key: "debt_id"
  belongs_to :ordem_servico, class_name: "OrdemServico", foreign_key: "os_id"
end

app/controllers/os_deb_tecnicos_controller.rb
class OsDebTecnicosController < ApplicationController
  before_action :set_os_deb_tecnico, only: [:show, :edit, :update, :destroy]

  # GET /os_deb_tecnicos
  # GET /os_deb_tecnicos.json
  def index
    @os_deb_tecnicos = OsDebTecnico.all
  end

  # GET /os_deb_tecnicos/1
  # GET /os_deb_tecnicos/1.json
  def show
  end

  # GET /os_deb_tecnicos/new
  def new
    ordem_servico  = OrdemServico.find(params[:os_id])
    @os_deb_tecnico = OsDebTecnico.new
    @os_deb_tecnico.ordem_servico= ordem_servico

  end

  # GET /os_deb_tecnicos/1/edit
  def edit
  end

  # POST /os_deb_tecnicos
  # POST /os_deb_tecnicos.json
  def create
    @os_deb_tecnico = OsDebTecnico.new(os_deb_tecnico_params)

    respond_to do |format|
      if @os_deb_tecnico.save
        format.html { redirect_to @os_deb_tecnico, notice: 'Os deb tecnico foi criado(a)' }
        format.json { render :show, status: :created, location: @os_deb_tecnico }
      else
        format.html { render :new }
        format.json { render json: @os_deb_tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /os_deb_tecnicos/1
  # PATCH/PUT /os_deb_tecnicos/1.json
  def update
    respond_to do |format|
      if @os_deb_tecnico.update(os_deb_tecnico_params)
        format.html { redirect_to @os_deb_tecnico, notice: 'Os deb tecnico foi atualizado(a)' }
        format.json { render :show, status: :ok, location: @os_deb_tecnico }
      else
        format.html { render :edit }
        format.json { render json: @os_deb_tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /os_deb_tecnicos/1
  # DELETE /os_deb_tecnicos/1.json
  def destroy
    @os_deb_tecnico.destroy
    respond_to do |format|
      format.html { redirect_to os_deb_tecnicos_url, notice: 'Os deb tecnico foi excluído(a)' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_os_deb_tecnico
      @os_deb_tecnico = OsDebTecnico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def os_deb_tecnico_params
      params.require(:os_deb_tecnico).permit(:debt_id, :os_id)
    end
end

app/helpers/os_deb_tecnicos_helper.rb
module OsDebTecnicosHelper
end

app/views/os_deb_tecnicos/_form.html.erb
<%= simple_form_for(@os_deb_tecnico) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :debt_id,:collection => DebitoTecnico.all,label_method: :nome,:label => "Débito Técnico" ,:include_blank => false %>
    <%= f.input :os_id, :as => :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/os_deb_tecnicos/_index.html.erb
<p id="notice"><%= notice %></p>

<h3>Débitos Técnicos da Ordem de Serviço</h3>

<table class="sortable table table-bordered table-hover table-condensed">

  <thead>
    <tr>
      <th>Débito Técnico</th>
      <th>Ordem de Serviço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordem_servico.os_deb_tecnicos.each do |os_deb_tecnico| %>
      <tr>
        <td><%= os_deb_tecnico.debito_tecnico.nome%></td>
        <td><%= os_deb_tecnico.ordem_servico.id %></td>
        <td><%= link_to '', os_deb_tecnico,class: "glyphicon glyphicon-zoom-in" %></td>
        <td><%= link_to '', edit_os_deb_tecnico_path(os_deb_tecnico),class: "glyphicon glyphicon-edit" %></td>
        <td><%= link_to '', os_deb_tecnico, method: :delete, data: { confirm: 'Você tem certeza?' },class: "glyphicon glyphicon-remove" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/os_deb_tecnicos/edit.html.erb
<h1>Editando Os Deb Tecnico</h1>

<%= render 'form' %>

<%= link_to '', @os_deb_tecnico %> |
<%= link_to 'Voltar', os_deb_tecnicos_path %>

app/views/os_deb_tecnicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Débitos Técnicos das Ordens de Serviço</h1>

<table class="sortable table table-bordered table-hover table-condensed">

  <thead>
    <tr>
      <th>Débito Técnico</th>
      <th>Ordem de Serviço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @os_deb_tecnicos.each do |os_deb_tecnico| %>
      <tr>
        <td><%= os_deb_tecnico.debito_tecnico.nome%></td>
        <td><%= os_deb_tecnico.ordem_servico.id %></td>
        <td><%= link_to '', os_deb_tecnico,class: "glyphicon glyphicon-zoom-in" %></td>
        <td><%= link_to '', edit_os_deb_tecnico_path(os_deb_tecnico),class: "glyphicon glyphicon-edit" %></td>
        <td><%= link_to '', os_deb_tecnico, method: :delete, data: { confirm: 'Você tem certeza?' },class: "glyphicon glyphicon-remove" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Os deb tecnico', new_os_deb_tecnico_path %>

app/views/os_deb_tecnicos/new.html.erb
<h1>Nova Os Deb Tecnico</h1>

<%= render 'form' %>


<% if (!params[:os_id].blank?) %>
  <%= link_to 'Voltar', controller:"ordem_servicos", action:"show", id: params[:os_id]  %>
<% else %>
  <a href="javascript:history.back()">Voltar</a>
<% end %>

app/views/os_deb_tecnicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Débito Técnico:</strong>
  <%= @os_deb_tecnico.debito_tecnico.nome %>
</p>

<p>
  <strong>Os:</strong>
  <%= @os_deb_tecnico.ordem_servico.id %>
</p>

<%= link_to '', edit_os_deb_tecnico_path(@os_deb_tecnico) %> |
<%= link_to 'Voltar', os_deb_tecnicos_path %>