config/routes.rb
Rails.application.routes.draw do
  resources :valor_usts

  authenticate :user do

    resources :os_tipos, only: [:new, :create, :edit, :update, :destroy]

    resources :os_tarefas do
      collection do
      get 'mostra_nao_pagas'
      get 'mostra_nao_pagas_aprovadas_os'
    end
end

    get '/set_situacao_tarefa' => 'os_tarefas#set_situacao', as: 'set_situacao_tarefa'
    resources :tarefa_deb_tecnicos

    resources :projetos

    resources :produtos

    resources :pessoas

    resources :os_nivel_servicos

    resources :os_entregavels

    resources :os_deb_tecnicos

    resources :ordem_servicos

    resources :entregavels

    resources :debito_tecnicos

    resources :catalogos

  end

  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :models


  root to: 'visitors#index'

  match 'imprimir', controller: 'ordem_servicos', action: 'imprimir', via: 'get'
  match 'clonar', controller: 'ordem_servicos', action: 'clone', via: 'get'
  match 'laudo', controller: 'laudos', action: 'laudo', via: 'get'

end

app/models/os_tarefa.rb
class OsTarefa < ActiveRecord::Base
  audited
  belongs_to :catalogo, class_name: "Catalogo", foreign_key: "catl_id"
  belongs_to :produto, class_name: "Produto", foreign_key: "prod_id"
  belongs_to :entregavel, class_name: "Entregavel", foreign_key: "entregavel_id"
  belongs_to :abriu_tarefa, class_name: "Pessoa", foreign_key: "pess_abertura_tarefa_id"
  belongs_to :atribuido_tarefa, class_name: "Pessoa", foreign_key: "pess_tarefa_atribuida_id"
  belongs_to :ordem_servico, class_name: "OrdemServico", foreign_key: "os_id"
  belongs_to :ordem_servico_pagamento, class_name: "OrdemServico", foreign_key: "id_os_pagamento"

  has_many :tarefa_deb_tecnicos, class_name: "TarefaDebTecnico", foreign_key: "tare_id",:dependent => :nullify

  def self.situacoes
      ['ACEITA','ACEITA COM RESSALVAS','REJEITADA','CANCELADA']
  end
end

app/controllers/os_tarefas_controller.rb
class OsTarefasController < ApplicationController
  before_action :set_os_tarefa, only: [:show, :edit, :update, :destroy]

  # GET /os_tarefas
  # GET /os_tarefas.json
  def index
    logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

    if params[:os_id]!=nil
      logger.debug "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"

      @os_tarefas = OsTarefa.where("id_os_pagamento = ?",params[:os_id])
    else
      @os_tarefas = OsTarefa.all
    end
  end

  # GET /os_tarefas/1
  # GET /os_tarefas/1.json
  def show
  end

  # GET /os_tarefas/new
  def new
    ordem_servico  = OrdemServico.find(params[:os_id])
    @os_tarefa = OsTarefa.new
    @os_tarefa.ordem_servico= ordem_servico

  end

  # GET /os_tarefas/1/edit
  def edit

  end

  # POST /os_tarefas
  # POST /os_tarefas.json
  def create
    @os_tarefa = OsTarefa.new(os_tarefa_params)

    respond_to do |format|
      if @os_tarefa.save
        if @os_tarefa.ordem_servico.id!=nil
          format.html { redirect_to "/ordem_servicos/"+@os_tarefa.ordem_servico.id.to_s, notice: 'A Tarefa foi criado(a)' }
          format.json { head :no_content }
        else
          format.html { redirect_to @os_tarefa, notice: 'A Tarefa foi criado(a)' }
          format.json { render :show, status: :created, location: @os_tarefa }
        end
      else
        format.html { render :new }
        format.json { render json: @os_tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /os_tarefas/1
  # PATCH/PUT /os_tarefas/1.json
  def update
    respond_to do |format|

      if @os_tarefa.update(os_tarefa_params)
        #se as situacao da tarefa nao for aceita, altera a ordem_servico_pagamento para null
        if(@os_tarefa.situacao!=OsTarefa.situacoes[0] && @os_tarefa.situacao!=OsTarefa.situacoes[1])

          @os_tarefa.ordem_servico_pagamento=nil
          @os_tarefa.save
        end

        if @os_tarefa.ordem_servico.id!=nil
          format.html { redirect_to "/ordem_servicos/"+@os_tarefa.ordem_servico.id.to_s, notice: 'A Tarefa foi atualizado(a)' }
          format.json { head :no_content }
        else
          format.html { redirect_to @os_tarefa, notice: 'A Tarefa foi atualizado(a)' }
          format.json { render :show, status: :ok, location: @os_tarefa }
        end
      else
        format.html { render :edit }
        format.json { render json: @os_tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /os_tarefas/1
  # DELETE /os_tarefas/1.json
  def destroy
    @os_tarefa.destroy
    respond_to do |format|
      if @os_tarefa.ordem_servico.id!=nil
        format.js   { render :layout => false }
        format.html { redirect_to "/ordem_servicos/"+@os_tarefa.ordem_servico.id.to_s, notice: 'Os tarefa foi excluído(a)' }
        format.json { head :no_content }
      else
        format.html { redirect_to os_tarefas_url, notice: 'A Tarefa foi excluído(a)' }
        format.json { head :no_content }
        format.js   { render :layout => false }

      end
    end
  end


  # TODO FAZER METODO PARA REJEITAR VARIAS TAREFAS SELECIONADAS VIA AJAX
  # SET_SITUACAO /os_tarefas/1
  # SET_SITUACAO/os_tarefas/1.json
  def set_situacao
    logger.debug "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"

      id_busca  = params[:id]
      @os_id  = params[:os_id]
      @os_tarefa  = OsTarefa.find(id_busca)
      @os_tarefa.situacao=params[:situacao]
      @ordem_servico = OrdemServico.find(@os_id)
      logger.debug "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"

      if @os_tarefa.situacao=='REJEITADA'
        @os_tarefa.ordem_servico_pagamento= nil
        @os_tarefa.situacao=OsTarefa.situacoes[2]
      else
        @os_tarefa.ordem_servico_pagamento= @ordem_servico
        @os_tarefa.situacao=OsTarefa.situacoes[0]
      end
      @os_tarefa.save
      respond_to do |format|

        format.json { head :no_content }
        format.js   { render :layout => false }

    end
  end

  #
  # lista tarefas que nao foram  pagas de outras OSs
  def mostra_nao_pagas
    @os_tarefas = OsTarefa.where("id_os_pagamento is null")
        @os_id  = params[:os_id]
        @titulo_nao_pagas=true

        @total_ust_tarefas = CalcTotalUstTarefasService.new(@os_tarefas, true).call
        @total_horas_tarefas=CalculaTotalHorasTarefasService.new(@os_tarefas, true).call
        render "os_tarefas/_index_tarefas_nao_pagas",
        locals: { os_tarefas: @os_tarefas },
        layout: false

  end

  #
  # lista tarefas que nao foram  pagas de outras OSs
  def mostra_nao_pagas_aprovadas_os

      @os_id  = params[:os_id]
      @titulo_nao_pagas=false
      @os_tarefas = OsTarefa.where("id_os_pagamento <> os_id and id_os_pagamento = ?",@os_id)

      @total_ust_tarefas = CalcTotalUstTarefasService.new(@os_tarefas, false).call
      @total_horas_tarefas=CalculaTotalHorasTarefasService.new(@os_tarefas, false).call
      render "os_tarefas/_index_tarefas_nao_pagas",
      locals: { os_tarefas: @os_tarefas },
      layout: false

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_os_tarefa
      @os_tarefa = OsTarefa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def os_tarefa_params
      params.require(:os_tarefa).permit(:os_id,:catl_id, :prod_id, :pess_abertura_tarefa_id, :pess_tarefa_atribuida_id, :entregavel_id, :id_tarefa_redmine, :ust_tarefa, :horastarefa, :situacao, :justificativa, :id_os_pagamento)
    end
end

app/helpers/os_tarefas_helper.rb
module OsTarefasHelper
end

app/views/os_tarefas/_form.html.erb
<%= simple_form_for(@os_tarefa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :catl_id,:collection => Catalogo.all.order(nome: :asc),label_method: :nome,:label => "Catálogo" ,:include_blank => false %>
    <%= f.input :prod_id,:collection => Produto.all.order(nome: :asc),label_method: :nome,:label => "Produto" ,:include_blank => false %>
    <%= f.input :pess_abertura_tarefa_id,:collection => Pessoa.all.order(nome: :asc),label_method: :nome,:label => "Abriu a Tarefa" ,:include_blank => false %>
    <%= f.input :pess_tarefa_atribuida_id,:collection => Pessoa.all.order(nome: :asc),label_method: :nome,:label => "Atribuído Para" ,:include_blank => false %>
    <%= f.input :entregavel_id,:collection => Entregavel.all,label_method: :nome,:label => "Entregável" ,:include_blank => true %>
    <%= f.input :os_id, :as => :hidden %>
    <%= f.input :id_os_pagamento %>
    <%= f.input :id_tarefa_redmine %>
    <%= f.input :ust_tarefa, label:'UST da tarefa:' %>
    <%= f.input :horastarefa, label:'Horas da tarefa:' %>
    <%= f.input :situacao,:collection => OsTarefa.situacoes,:label => "Situações" , :include_blank => false %>
    <%= f.input :justificativa, label:'Justificativa:' %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/os_tarefas/_index.html.erb
<%= javascript_tag do %>
  $( document ).ready(function() {
    var id_os = $("#id_Os").data("value");
      $("#tarefas_nao_pagas").load("/os_tarefas/mostra_nao_pagas?os_id=<%= @ordem_servico.id %>");
      $("#mostra_nao_pagas_aprovadas_os").load("/os_tarefas/mostra_nao_pagas_aprovadas_os?os_id=<%= @ordem_servico.id %>");

  });

<% end %>

<p id="notice"><%= notice %></p>

<h3>Tarefas da Ordem de Serviço</h3>

<table class="sortable sortable table table-bordered table-hover table-condensed">

  <thead>
    <tr>
      <th>#</th>
      <% if @ordem_servico.os_tipo.id==4 || @ordem_servico.os_tipo.id==5 || @ordem_servico.os_tipo.id==7%>
      <th>Catálogo</th>
      <% end %>
      <th>Produto</th>
      <th>Abriu Tarefa</th>
      <th>Tarefa Atribuida para</th>
      <th>Entregável</th>
      <th>Id Tarefa Redmnine</th>
      <th>UST Tarefa</th>
      <th>Horas Tarefa</th>
      <th>Situação</th>
      <th>Justificativa</th>

      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordem_servico.os_tarefas.each_with_index do |os_tarefa, index| %>
      <tr>
        <td><%= index +1%></td>
        <% if @ordem_servico.os_tipo.id==4 || @ordem_servico.os_tipo.id==5 || @ordem_servico.os_tipo.id==7%>
        <td><%= os_tarefa.catalogo.nome %></td>
        <% end %>
        <%if os_tarefa.produto  %>
        <td><%= os_tarefa.produto.nome %></td>
        <% else %>
        <td> </td>
        <% end %>
        <%if !os_tarefa.abriu_tarefa.blank?  %>
          <td><%= os_tarefa.abriu_tarefa.nome %></td>
        <% else %>
          <td> </td>
        <% end %>
        <%if !os_tarefa.atribuido_tarefa.blank?  %>
          <td><%= os_tarefa.atribuido_tarefa.nome %></td>
        <% else %>
          <td> </td>
        <% end %>
        <%if os_tarefa.entregavel  %>
        <td><%= os_tarefa.entregavel.nome %></td>
        <% else %>
        <td> </td>
        <% end %>
        <%if os_tarefa.id_tarefa_redmine  %>
        <td><a href="https://projetos.tce.go.gov.br/issues/<%=  "%g" % os_tarefa.id_tarefa_redmine %>"><%= "%g" % os_tarefa.id_tarefa_redmine.to_s %></a> </td>
        <% else %>
        <td> </td>
        <% end %>
        <td><%= os_tarefa.ust_tarefa %></td>
        <td><%= os_tarefa.horastarefa %></td>
        <td><%= os_tarefa.situacao %></td>
        <td><%= os_tarefa.justificativa%></td>
        <td><%= link_to '', os_tarefa,class: "glyphicon glyphicon-zoom-in" %></td>
        <td><%= link_to '', edit_os_tarefa_path(os_tarefa),class: "glyphicon glyphicon-edit" %></td>
        <td><%= link_to '', os_tarefa, method: :delete, data: { confirm: 'Você tem certeza?' }, :remote => true, class: "delete_item glyphicon glyphicon-remove" %></td>
        <td><%= link_to 'Inserir Débito Técnico', new_tarefa_deb_tecnico_path(tare_id: os_tarefa.id), class: '' %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <strong>Total de UST das Tarefas Aceitas:</strong>
  <%= @total_ust_tarefas %>
</p>
<p>
  <strong>Total de Horas das Tarefas Aceitas:</strong>
  <%= @total_horas_tarefas %>
</p>
<br>
<div id="mostra_nao_pagas_aprovadas_os">
</div>
<div id="tarefas_nao_pagas">
</div>

app/views/os_tarefas/_index_tarefas_nao_pagas.html.erb
<%if @titulo_nao_pagas  %>
<h3>Tarefas Pendentes e não pagas</h3>
<% else %>
<h3>Tarefas Pendentes Incluídas nesta OS</h3>
<% end %>


<table class="sortable sortable table table-bordered table-hover table-condensed">

  <thead>
    <tr>
      <th>#</th>
      <th>OS Originária</th>
      <th>Catálogo</th>
      <th>Produto</th>
      <th>Abriu Tarefa</th>
      <th>Tarefa Atribuida para</th>
      <th>Entregável</th>
      <th>Id Tarefa Redmnine</th>
      <th>UST Tarefa</th>
      <th>Horas Tarefa</th>
      <th>Situação</th>
      <th>Justificativa</th>

      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @os_tarefas.each_with_index do |os_tarefa, index| %>
      <tr>
        <td><%= index +1%></td>
        <td><a href="/ordem_servicos/<%= os_tarefa.ordem_servico.id%>"><%= os_tarefa.ordem_servico.id%></a> </td>
        <td><%= os_tarefa.catalogo.nome %></td>
        <%if os_tarefa.produto  %>
        <td><%= os_tarefa.produto.nome %></td>
        <% else %>
        <td> </td>
        <% end %>
        <%if !os_tarefa.abriu_tarefa.blank?  %>
          <td><%= os_tarefa.abriu_tarefa.nome %></td>
        <% else %>
          <td> </td>
        <% end %>
        <%if !os_tarefa.atribuido_tarefa.blank?  %>
          <td><%= os_tarefa.atribuido_tarefa.nome %></td>
        <% else %>
          <td> </td>
        <% end %>
        <%if os_tarefa.entregavel  %>
        <td><%= os_tarefa.entregavel.nome %></td>
        <% else %>
        <td> </td>
        <% end %>
        <%if os_tarefa.id_tarefa_redmine  %>
        <td><a href="https://projetos.tce.go.gov.br/issues/<%=  "%g" % os_tarefa.id_tarefa_redmine %>"><%= "%g" % os_tarefa.id_tarefa_redmine.to_s %></a> </td>
        <% else %>
        <td> </td>
        <% end %>
        <td><%= os_tarefa.ust_tarefa %></td>
        <td><%= os_tarefa.horastarefa %></td>
        <td><%= os_tarefa.situacao %></td>
        <td><%= os_tarefa.justificativa%></td>


        <td><%= link_to '', os_tarefa,class: "glyphicon glyphicon-zoom-in" %></td>
        <td><%= link_to '', edit_os_tarefa_path(os_tarefa),class: "glyphicon glyphicon-edit" %></td>
        <td><%= link_to '', os_tarefa, method: :delete, data: { confirm: 'Você tem certeza?' }, :remote => true, class: "delete_item glyphicon glyphicon-remove" %></td>
        <%if @titulo_nao_pagas   %>
        <td><%= link_to '', set_situacao_tarefa_url(id: os_tarefa.id, os_id:@os_id, situacao:'ACEITA'), method: :get, :remote => true,:title => 'Aceitar Tarefa', class: "set_item glyphicon glyphicon-thumbs-up" %></td>
        <% else %>
        <td><%= link_to '', set_situacao_tarefa_url(id: os_tarefa.id, os_id:@os_id, situacao:'REJEITADA'), method: :get, :remote => true,:title => 'Rejeitar Tarefa', class: "set_item glyphicon glyphicon-thumbs-down" %></td>
        <% end %>

        <td><%= link_to 'Inserir Débito Técnico', new_tarefa_deb_tecnico_path(tare_id: os_tarefa.id), class: '' %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <strong>Total UST das Tarefas:</strong>
  <%= @total_ust_tarefas %>
</p>
<p>
  <strong>Total de Horas das Tarefas:</strong>
  <%= @total_horas_tarefas %>
</p>
<br>

app/views/os_tarefas/destroy.js.erb
$('.delete_item').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});

app/views/os_tarefas/edit.html.erb
<h1>Editando Os Tarefa</h1>

<%= render 'form' %>

<%= link_to '', @os_tarefa %> |
<%= link_to 'Voltar', os_tarefas_path %>

app/views/os_tarefas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Tarefas das Ordens de Serviço</h1>

<table class="sortable sortable table table-bordered table-hover table-condensed">

  <thead>
    <tr>
      <th>Catálogo</th>
      <th>Produto</th>
      <th>Abriu Tarefa</th>
      <th>Tarefa Atribuida para</th>
      <th>Entregável</th>
      <th>OS</th>
      <th>Id Tarefa Redmnine</th>
      <th>UST Tarefa</th>
      <th>Horas Tarefa</th>
      <th>Situação</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @os_tarefas.each_with_index do |os_tarefa, index| %>
      <tr>
        <td><%= index %></td>
        <td><%= os_tarefa.catalogo.nome %></td>
        <%if os_tarefa.produto  %>
        <td><%= os_tarefa.produto.nome %></td>
        <% else %>
        <td> </td>
        <% end %>
        <%if os_tarefa.abriu_tarefa.nome  %>
        <td><%= os_tarefa.abriu_tarefa.nome %></td>
        <% else %>
        <td> </td>
        <% end %>
        <td><%= os_tarefa.atribuido_tarefa.nome %></td>
        <%if os_tarefa.entregavel  %>
        <td><%= os_tarefa.entregavel.nome %></td>
        <% else %>
        <td> </td>
        <% end %>
        <td><%= os_tarefa.ordem_servico.projeto.nome %></td>
        <td><%= os_tarefa.id_tarefa_redmine %></td>
        <td><%= os_tarefa.ust_tarefa %></td>
        <td><%= os_tarefa.horastarefa %></td>
        <td><%= os_tarefa.situacao %></td>
        <td><%= link_to '', os_tarefa,class: "glyphicon glyphicon-zoom-in" %></td>
        <td><%= link_to '', edit_os_tarefa_path(os_tarefa),class: "glyphicon glyphicon-edit" %></td>
        <td><%= link_to '', os_tarefa, method: :delete, data: { confirm: 'Você tem certeza?' },class: "glyphicon glyphicon-remove" %></td>
        <td><%= link_to 'Inserir Débito Técnico', new_tarefa_deb_tecnico_path(tare_id: os_tarefa.id), class: '' %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Os tarefa', new_os_tarefa_path %>

app/views/os_tarefas/new.html.erb
<h1>Nova Tarefa de O.S.</h1>

<%= render 'form' %>

<% if (!params[:os_id].blank?) %>
<%= link_to 'Voltar', controller:"ordem_servicos", action:"show", id: params[:os_id]  %>
<% else %>
<a href="javascript:history.back()">Voltar</a>
<% end %>

app/views/os_tarefas/set_situacao.js.erb
alert("hi!")
$("#tarefas_nao_pagas").load("/os_tarefas/mostra_nao_pagas?os_id=<%= @ordem_servico.id %>");
$("#mostra_nao_pagas_aprovadas_os").load("/os_tarefas/mostra_nao_pagas_aprovadas_os?os_id=<%= @ordem_servico.id %>");

app/views/os_tarefas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Catalogo:</strong>
  <%= @os_tarefa.catalogo.nome %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @os_tarefa.produto.nome %>
</p>

<p>
  <strong>Pessoa abertura tarefa:</strong>
  <%= @os_tarefa.abriu_tarefa.nome %>
</p>

<p>
  <strong>Tarefa atribuida:</strong>
  <%= @os_tarefa.atribuido_tarefa.nome %>
</p>

<%if @os_tarefa.entregavel  %>
  <strong>Entregavel:</strong>
  <%= @os_tarefa.entregavel.nome %>
<% else %>

  <strong>Entregavel:</strong>


<% end %>


<p>
  <strong>Os:</strong>
  <%= @os_tarefa.ordem_servico.descricao %>
</p>

<p>
  <strong>Id tarefa redmnine:</strong>
  <%= @os_tarefa.id_tarefa_redmine %>
</p>

<p>
  <strong>Ust tarefa:</strong>
  <%= @os_tarefa.ust_tarefa %>
</p>

<p>
  <strong>Nurm horastarefa:</strong>
  <%= @os_tarefa.horastarefa %>
</p>

<p>
  <strong>Situação:</strong>
  <%= @os_tarefa.situacao %>
</p>

<p>
  <strong>Justificativa:</strong>
  <%= @os_tarefa.justificativa %>
</p>
<br>
<br>
<%= render "tarefa_deb_tecnicos/index" %>
<%= link_to 'Inserir Débito Técnico', new_tarefa_deb_tecnico_path(tare_id: @os_tarefa.id), class: 'btn btn-default' %>


<br>
<%= link_to 'Editar', edit_os_tarefa_path(@os_tarefa) %> |
<a href="javascript:history.back()">Voltar</a>