config/routes.rb
Rails.application.routes.draw do
  resources :valor_usts

  authenticate :user do

    resources :os_tipos, only: [:new, :create, :edit, :update, :destroy]

    resources :os_tarefas do
      collection do
      get 'mostra_nao_pagas'
      get 'mostra_nao_pagas_aprovadas_os'
    end
end

    get '/set_situacao_tarefa' => 'os_tarefas#set_situacao', as: 'set_situacao_tarefa'
    resources :tarefa_deb_tecnicos

    resources :projetos

    resources :produtos

    resources :pessoas

    resources :os_nivel_servicos

    resources :os_entregavels

    resources :os_deb_tecnicos

    resources :ordem_servicos

    resources :entregavels

    resources :debito_tecnicos

    resources :catalogos

  end

  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :models


  root to: 'visitors#index'

  match 'imprimir', controller: 'ordem_servicos', action: 'imprimir', via: 'get'
  match 'clonar', controller: 'ordem_servicos', action: 'clone', via: 'get'
  match 'laudo', controller: 'laudos', action: 'laudo', via: 'get'

end

app/models/os_entregavel.rb
class OsEntregavel < ActiveRecord::Base
  audited
  belongs_to :entregavel, class_name: "Entregavel", foreign_key: "entregavel_id"
  belongs_to :ordem_servico, class_name: "OrdemServico", foreign_key: "os_id"

  def self.situacoes
      ['ACEITO','ACEITO COM RESSALVAS','REJEITADO', 'NÃO ENTREGUE','CANCELADO']
  end
end

app/controllers/os_entregavels_controller.rb
class OsEntregavelsController < ApplicationController
  before_action :set_os_entregavel, only: [:show, :edit, :update, :destroy]

  # GET /os_entregavels
  # GET /os_entregavels.json
  def index
    @os_entregavels = OsEntregavel.all

  end

  # GET /os_entregavels/1
  # GET /os_entregavels/1.json
  def show
  end

  # GET /os_entregavels/new
  def new

    ordem_servico  = OrdemServico.find(params[:os_id])
    @os_entregavel = OsEntregavel.new
    @os_entregavel.ordem_servico= ordem_servico
  end

  # GET /os_entregavels/1/edit
  def edit
  end

  # POST /os_entregavels
  # POST /os_entregavels.json
  def create
    @os_entregavel = OsEntregavel.new(os_entregavel_params)

    respond_to do |format|
      if @os_entregavel.save
        if @os_entregavel.ordem_servico.id!=nil
          format.html { redirect_to "/os_entregavels/new?os_id="+@os_entregavel.ordem_servico.id.to_s, notice: 'Entregável criado com sucesso na O.S.' }
          format.json { render :show, status: :created, location: @os_entregavel }
        else
          format.html { redirect_to @os_entregavel, notice: 'Entregável criado com sucesso na O.S' }
          format.json { render :show, status: :created, location: @os_entregavel }
        end
      else
        format.html { render :new }
        format.json { render json: @os_entregavel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /os_entregavels/1
  # PATCH/PUT /os_entregavels/1.json
  def update
    respond_to do |format|
      if @os_entregavel.update(os_entregavel_params)
        if @os_entregavel.ordem_servico.id!=nil
          format.html { redirect_to "/ordem_servicos/"+@os_entregavel.ordem_servico.id.to_s, notice: 'Os entregavel foi atualizado(a)' }
          format.json { head :no_content }
        else
          format.html { redirect_to @os_entregavel, notice: 'Os entregavel foi atualizado(a)' }
          format.json { render :show, status: :ok, location: @os_entregavel }
        end
      else
        format.html { render :edit }
        format.json { render json: @os_entregavel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /os_entregavels/1
  # DELETE /os_entregavels/1.json
  def destroy
    @os_entregavel.destroy
    respond_to do |format|
      if @os_entregavel.ordem_servico.id!=nil
        format.html { redirect_to "/ordem_servicos/"+@os_entregavel.ordem_servico.id.to_s, notice: 'Os entregavel foi excluído(a)' }
        format.json { head :no_content }
      else
        format.html { redirect_to os_entregavels_url, notice: 'Os entregavel foi excluído(a)' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_os_entregavel
      @os_entregavel = OsEntregavel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def os_entregavel_params
      params.require(:os_entregavel).permit(:entregavel_id, :os_id, :ust_previsto, :situacao, :justificativa)
    end
end

app/helpers/os_entregavels_helper.rb
module OsEntregavelsHelper
end

app/views/os_entregavels/_form.html.erb
<%= simple_form_for(@os_entregavel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :entregavel_id,:collection => Entregavel.all.order('nome ASC'),label_method: :nome,:label => "Entregável" ,:include_blank => false  %>
    <%= f.input :os_id, :as => :hidden %>
    <%= f.input :ust_previsto %>
    <%= f.input :situacao,:collection => OsEntregavel.situacoes,:label => "Situações" , :include_blank => false %>
    <%= f.input :justificativa, label:'Justificativa:' %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/os_entregavels/_index.html.erb
<p id="notice"><%= notice %></p>

<h3>Entregáveis de Ordens de Serviço</h3>

<table class="sortable table table-bordered table-hover table-condensed">

  <thead>
    <tr>
      <th>#</th>
      <th>Entregavel</th>
      <th>Ust previsto</th>
      <th>Situação</th>
      <th>Justificativa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordem_servico.os_entregavels.each_with_index do |os_entregavel, index| %>
      <tr>
        <td><%= index +1%></td>
        <td><%= os_entregavel.entregavel.nome %></td>
        <td><%= os_entregavel.ust_previsto %></td>
        <td><%= os_entregavel.situacao %></td>
        <td><%= os_entregavel.justificativa %></td>
        <td><%= link_to '', os_entregavel,class: "glyphicon glyphicon-zoom-in" %></td>
        <td><%= link_to '', edit_os_entregavel_path(os_entregavel),class: "glyphicon glyphicon-edit" %></td>
        <td><%= link_to '', os_entregavel, method: :delete, data: { confirm: 'Você tem certeza?' },class: "glyphicon glyphicon-remove" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <strong>Total UST:</strong>
  <%= @total_ust %>
</p>


<br>

app/views/os_entregavels/edit.html.erb
<h1>Editando Os Entregavel</h1>

<%= render 'form' %>

<%= link_to '', @os_entregavel %> |
<%= link_to 'Voltar', os_entregavels_path %>

app/views/os_entregavels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Entregáveis de Ordens de Serviço</h1>

<table class="sortable table table-bordered table-hover table-condensed">

  <thead>
    <tr>
      <th>Entregavel</th>
      <th>Osi d</th>
      <th>Ust previsto</th>
      <th>Situação</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @os_entregavels.each do |os_entregavel| %>
      <tr>
        <td><%= os_entregavel.entregavel.nome %></td>
        <td><%= os_entregavel.ordem_servico.id %></td>
        <td><%= os_entregavel.ust_previsto %></td>
        <th><%= os_entregavel.situacao %></th>
        <td><%= link_to '', os_entregavel,class: "glyphicon glyphicon-zoom-in" %></td>
        <td><%= link_to '', edit_os_entregavel_path(os_entregavel),class: "glyphicon glyphicon-edit" %></td>
        <td><%= link_to '', os_entregavel, method: :delete, data: { confirm: 'Você tem certeza?' },class: "glyphicon glyphicon-remove" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Os entregavel', new_os_entregavel_path %>

app/views/os_entregavels/new.html.erb
<h1>Nova Os Entregavel</h1>

<%= render 'form' %>

<% if (!params[:os_id].blank?) %>
<%= link_to 'Voltar', controller:"ordem_servicos", action:"show", id: params[:os_id]  %>
<% else %>
<a href="javascript:history.back()">Voltar</a>
<% end %>

app/views/os_entregavels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entregavel:</strong>
  <%= @os_entregavel.entregavel.nome %>
</p>

<p>
  <strong>Ordem de Serviço:</strong>
  <%= @os_entregavel.ordem_servico.id %>
</p>

<p>
  <strong>Ust previsto:</strong>
  <%= @os_entregavel.ust_previsto %>
</p>
<p>
  <strong>Situação:</strong>
  <%= @os_entregavel.situacao %>
</p>
<p>
  <strong>Justificativa:</strong>
  <%= @os_entregavel.justificativa %>
</p>
<%= link_to '', edit_os_entregavel_path(@os_entregavel) %> |
<%= link_to 'Voltar', ordem_servicos_path %>