config/routes.rb
Rails.application.routes.draw do
  resources :valor_usts

  authenticate :user do

    resources :os_tipos, only: [:new, :create, :edit, :update, :destroy]

    resources :os_tarefas do
      collection do
      get 'mostra_nao_pagas'
      get 'mostra_nao_pagas_aprovadas_os'
    end
end

    get '/set_situacao_tarefa' => 'os_tarefas#set_situacao', as: 'set_situacao_tarefa'
    resources :tarefa_deb_tecnicos

    resources :projetos

    resources :produtos

    resources :pessoas

    resources :os_nivel_servicos

    resources :os_entregavels

    resources :os_deb_tecnicos

    resources :ordem_servicos

    resources :entregavels

    resources :debito_tecnicos

    resources :catalogos

  end

  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :models


  root to: 'visitors#index'

  match 'imprimir', controller: 'ordem_servicos', action: 'imprimir', via: 'get'
  match 'clonar', controller: 'ordem_servicos', action: 'clone', via: 'get'
  match 'laudo', controller: 'laudos', action: 'laudo', via: 'get'

end

app/models/os_tipo.rb
class OsTipo < ActiveRecord::Base
    audited
    has_many :ordem_servicos, class_name: "OrdemServico", foreign_key: "tipo_os_id"


    def self.tipos
        ['CONSTRUÇÃO', 'MANUTENÇÃO', 'INFRA', 'BANCO', 'SUPORTE','PROJETO','DOCUMENTAÇÃO']
    end

end

app/controllers/os_tipos_controller.rb
class OsTiposController < ApplicationController
  before_action :set_os_tipo, only: [:show, :edit, :update, :destroy]

  # GET /os_tipos
  # GET /os_tipos.json
  def index
    @os_tipos = OsTipo.all
  end

  # GET /os_tipos/1
  # GET /os_tipos/1.json
  def show
  end

  # GET /os_tipos/new
  def new
    @os_tipo = OsTipo.new
  end

  # GET /os_tipos/1/edit
  def edit
  end

  # POST /os_tipos
  # POST /os_tipos.json
  def create
    @os_tipo = OsTipo.new(os_tipo_params)

    respond_to do |format|
      if @os_tipo.save
        format.html { redirect_to @os_tipo, notice: 'Os tipo foi criado(a)' }
        format.json { render :show, status: :created, location: @os_tipo }
      else
        format.html { render :new }
        format.json { render json: @os_tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /os_tipos/1
  # PATCH/PUT /os_tipos/1.json
  def update
    respond_to do |format|
      if @os_tipo.update(os_tipo_params)
        format.html { redirect_to @os_tipo, notice: 'Os tipo foi atualizado(a)' }
        format.json { render :show, status: :ok, location: @os_tipo }
      else
        format.html { render :edit }
        format.json { render json: @os_tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /os_tipos/1
  # DELETE /os_tipos/1.json
  def destroy
    @os_tipo.destroy
    respond_to do |format|
      format.html { redirect_to os_tipos_url, notice: 'Os tipo foi excluído(a)' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_os_tipo
      @os_tipo = OsTipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def os_tipo_params
      params.require(:os_tipo).permit(:nome)
    end
end

app/helpers/os_tipos_helper.rb
module OsTiposHelper
end

app/views/os_tipos/_form.html.erb
<%= simple_form_for(@os_tipo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome,:collection => OsTipo.tipos,:label => "Tipos" ,:include_blank => false %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/os_tipos/edit.html.erb
<h1>Editando Os Tipo</h1>

<%= render 'form' %>

<%= link_to '', @os_tipo %> |
<%= link_to 'Voltar', os_tipos_path %>

app/views/os_tipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Os Tipos</h1>

<table class="sortable table table-bordered table-hover table-condensed">

  <thead>
    <tr>
      <th>Os tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @os_tipos.each do |os_tipo| %>
      <tr>
        <td><%= os_tipo.nome %></td>
        <td><%= link_to '', os_tipo,class: "glyphicon glyphicon-zoom-in" %></td>
        <td><%= link_to '', edit_os_tipo_path(os_tipo),class: "glyphicon glyphicon-edit" %></td>
        <td><%= link_to '', os_tipo, method: :delete, data: { confirm: 'Você tem certeza?' },class: "glyphicon glyphicon-remove" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Os tipo', new_os_tipo_path %>

app/views/os_tipos/new.html.erb
<h1>Nova Os Tipo</h1>

<%= render 'form' %>

<%= link_to 'Voltar', os_tipos_path %>

app/views/os_tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Os tipo:</strong>
  <%= @os_tipo.nome %>
</p>

<%= link_to 'Editar', edit_os_tipo_path(@os_tipo) %> |
<%= link_to 'Voltar', os_tipos_path %>